---
output:
  pdf_document:
    fig_caption: true
    latex_engine: xelatex
    keep_tex: yes
header-includes:
   - \usepackage{booktabs}
   - \usepackage[font={small},labelfont=bf,labelsep=colon]{caption}
   - \linespread{1.05}
   - \usepackage[compact]{titlesec}
   - \usepackage{enumitem}
   - \usepackage{tikz}
   - \def\checkmark{\tikz\fill[scale=0.4](0,.35) -- (.25,0) -- (1,.7) -- (.25,.15) -- cycle;}
   - \setlist{nolistsep}
   - \titlespacing{\section}{2pt}{*0}{*0}
   - \titlespacing{\subsection}{2pt}{*0}{*0}
   - \titlespacing{\subsubsection}{2pt}{*0}{*0}
   - \setlength{\parskip}{6pt}
fontsize: 11pt
mainfont: Arial
geometry: margin=0.8in
---

<!--
   - \setlength{\parskip}{3pt}
   - \setlength{\topsep}{0pt}
   - \setlength{\partopsep}{0pt}
   - \setlength{\itemsep}{0pt}
   - \setlength{\floatsep}{0pt}
   - \setlength{\intextsep}{2pt}
   - \setlength{\abovecaptionskip}{2pt}
   - \setlength{\belowcaptionskip}{0pt}
-->


```{r setup, include=FALSE}
knitr::opts_chunk$set( cache=TRUE )
```

\pagenumbering{gobble}

__Nicholas J. Tustison, DSc__

<!--
-->

_Describe engagement with learners in your mission area of excellence
(clinical, research, education, community)._

I am a co-founder and developer of the widely recognized open-source Advanced
Normalization Tools Ecosystem (ANTsX) which allows me to simultaneously engage
with learners and contribute to ongoing research.  This has led to significant
opportunities for mentoring and teaching students, post-graduate trainees, and
other researchers by providing numerous tutorials and workshops at various
conferences and at different academic and scientific institutions.  I have also
organized this tutorial material for online public access.  This is in addition
to my daily participation in the ANTsX online user forums.

_Give a brief self-evaluation regarding adherence to ASPIRE values. You should
describe your contributions to at least one of the ASPIRE values
(Accountability, Stewardship, Professionalism, Integrity, Respect, Equity)._

My approach to research and collaboration is guided by a deep commitment to the
development of high-quality, open-source computational strategies for biological
and medical imaging.  I believe that such commitments create a supportive and
inclusive environment where knowledge is shared, diverse perspectives are
valued, and the quality of work is held to the highest standards.  Their
importance has only increased since returning to the University of Virginia in
2010 as an Assistant Professor and subsequently during my current tenure as an
Associate Professor.

__Personal Statement__

Throughout my academic career, I have benefited from caring mentors who have
demonstrated excellent academic scholarship and integrity while promoting values
of mutual respect.  As an example, I continue to benefit immensely from
relationships developed during my initial post-graduate years at the PICSL lab,
particularly those at the University of Pennsylvania in the Penn Image and
Computing Science Laboratory under the direction of Dr. James C. Gee.  While at
the University of Pennsylvania, my colleague, Dr. Brian B. Avants, and I
co-founded the open-source Advanced Normalization Tools Ecosystem (ANTsX).  This
software suite has evolved to become one of the most widely used and highly
cited libraries in the field.  Recently, we have leveraged ANTs development in
the successful application of two explicitly ANTs-based NIH R01 grants.

One of the benefits of being a part of a premier research university are the
many opportunities for collaboration with internationally recognized scientists
targeting a variety of clinical applications.  As one of the leading
institutions in the field of functional lung imaging using hyperpolarized gases,
I have been part of a research team making important algorithmic contributions
to the field which have been recently made available as a large-scale community
resource (www.xenonanalysis.com).  Analagous quantitative contributions have
been made in the field of traumatic brain injury with Dr. James Stone and Dr.
Avants. This research and development strategy has also resulted in an expansion
of the circle of my collaborators beyond the University of Virginia to include
collaborations with people at such academic entities and scientific institutions
as the University of California, Irvine, the University of Pennsylvania, and the
Allen Brain Institute.

In parallel with the appreciation I have for my many external opportunities for
collaboration and mentoring, I am honored to be associated with the University
of Virginia and feel extremely fortunate to work with its high quality faculty
in exploring fascinating research questions.  I look forward to continuing my
academic career at UVa where I can best provide the necessary expertise for
biological and medical imaging data science.



<!--
Describe engagement with learners in your mission area of excellence (clinical,
research, education, community).

Give a brief self-evaluation regarding
adherence to ASPIRE values. You should describe your contributions to at least
one of the ASPIRE values (Accountability, Stewardship, Professionalism,
Integrity, Respect, Equity).
-->

