---
output:
  pdf_document:
    fig_caption: true
    latex_engine: xelatex
    keep_tex: yes
header-includes:
   - \usepackage{booktabs}
   - \usepackage[font={small},labelfont=bf,labelsep=colon]{caption}
   - \linespread{1.05}
   - \usepackage[compact]{titlesec}
   - \usepackage{enumitem}
   - \usepackage{tikz}
   - \def\checkmark{\tikz\fill[scale=0.4](0,.35) -- (.25,0) -- (1,.7) -- (.25,.15) -- cycle;}
   - \setlist{nolistsep}
   - \titlespacing{\section}{2pt}{*0}{*0}
   - \titlespacing{\subsection}{2pt}{*0}{*0}
   - \titlespacing{\subsubsection}{2pt}{*0}{*0}
   - \setlength{\parskip}{6pt}
bibliography:
csl:
fontsize: 12pt
mainfont: Georgia
geometry: margin=1.0in
---

<!--
   - \setlength{\parskip}{3pt}
   - \setlength{\topsep}{0pt}
   - \setlength{\partopsep}{0pt}
   - \setlength{\itemsep}{0pt}
   - \setlength{\floatsep}{0pt}
   - \setlength{\intextsep}{2pt}
   - \setlength{\abovecaptionskip}{2pt}
   - \setlength{\belowcaptionskip}{0pt}
-->


<style type="text/css">
body,
code.bash{
  font-size: 8px;
}
pre {
  font-size: 8px
}
</style>

<!-- https://grants.nih.gov/grants/ElectronicReceipt/pdf_guidelines.htm -->


```{r setup, include=FALSE}
knitr::opts_chunk$set( cache=TRUE )
```

\pagenumbering{gobble}

<!--
https://faculty.med.virginia.edu/facultyaffairs/files/2015/05/Referee-letter-criteria-15-April-2015.pdf
-->

# Independent referees

<!--
* Michael Yassa, Associate Professor, UC Irvine, myassa@uci.edu, (949) 824-1687
-->

* Paul Thompson, Professor, University of Southern California,  pthomp@usc.edu, 323-442-7246
* Craig Stark, Professor, UC Irvine, starklab@uci.edu, (949) 824-4230
* Jason Woods, Professor, University of Cincinnati, Jason.Woods@cchmc.org, (513) 803-4463
* Grace Parraga, Professor, Western University, gparraga@robarts.ca, (519) 931-5265
* Martin Styner, Associate Professor, University of North Carolina, styner@unc.edu, 919 590 6209
* Simon Warfield, Professor, Harvard Medical School, simon.warfield@childrens.harvard.edu, (617) 355-4566
* Alejandro Frangi, Professor, University of Sheffield, a.frangi@sheffield.ac.uk, +44 114 2220153
* Sean Fain, Associate Professor, University of Wisconsin-Madison, sfain@wisc.edu, (608) 263-0090
* Jim Wild, Professor, University of Sheffield, j.m.wild@sheffield.ac.uk, +44 (0) 114 215 9141
* Nicholas Ayache, Professor, INRIA,  Nicholas.Ayache@inria.fr   (X - BRATS paper)
* Ron Kikinis, Professor, Harvard Medical School, kikinis@bwh.harvard.edu, +1 617.732.7389
* Daniel Rueckert, Professor, Imperial College London, d.rueckert@imperial.ac.uk, +44 20 75948333
* Samuel E. Gandy, Professor, The Mount Sinai Hospital, samuel.gandy@mssm.edu, 212-241-7076


# Possible independent referees (co-authors on competition papers)
* Josien Pluim, Professor, Eindhoven University of Technology, j.pluim@tue.nl, +31 40 - 247 8853             (X - EMPIRE paper)
* D. Louis Collins,  Professor, McGill University, louis.collins@mcgill.ca, 1 514–398–4227       (X - BRATS paper)
* Erin Bigler, Professor, Brigham Young University, erin_bigler@byu.edu, 801-422-4289                   (X - WMH paper)
* Dawn Elliot, Professor, University of Delaware, delliott@udel.edu,                 (X - Jonathon's paper)
* Mauricio Reyes, Associate Professor, University of Bern, mauricio.reyes@istb.unibe.ch, (+41) 31 631 59 20 (X - BRATS paper)
* Edward DiBella, Professor, University of Utah, edward.dibella@hsc.utah.edu, (801) 585-5543       (X - the group cardiac paper)
* Alistair Young, Professor, University of Auckland, a.young@auckland.ac.nz, +64 9 923 6115     (X - the group cardiac paper)


<!--
# External referees

* James C. Gee, Associate Professor, University of Pennsylvania, gee@mail.med.upenn.edu, 215-746-6295
* Amir A. Amini, Professor, University of Louisville, amir.amini@louisville.edu, (502) 852 4767
* Talissa A. Altes, Professor, University of Missouri-Columbia, altest@health.missouri.edu, (573) 882-1026
* Khader Hassan, Associate Professor, University of Texas Health Science Center at Houston, (713) 500-7684

# Internal referees

* John P. Mugler, Professor, University of Virginia, jpm7r@virginia.edu
* James R. Stone, Associate Professor, University of Virginia
* Fred Epstein, Professor, University of Virginia
-->
