---
output:
  pdf_document:
    fig_caption: true
    latex_engine: xelatex
    keep_tex: yes
header-includes:
   - \usepackage{booktabs}
   - \usepackage[font={small},labelfont=bf,labelsep=colon]{caption}
   - \linespread{1.1}
   - \usepackage[compact]{titlesec}
   - \usepackage{enumitem}
   - \usepackage{tikz}
   - \def\checkmark{\tikz\fill[scale=0.4](0,.35) -- (.25,0) -- (1,.7) -- (.25,.15) -- cycle;}
   - \setlist{nolistsep}
   - \titlespacing{\section}{2pt}{*0}{*0}
   - \titlespacing{\subsection}{2pt}{*0}{*0}
   - \titlespacing{\subsubsection}{2pt}{*0}{*0}
   - \setlength{\parskip}{6pt}
bibliography:
csl:
fontsize: 11pt
mainfont: Georgia
geometry: margin=1.0in
---

<!--
   - \setlength{\parskip}{3pt}
   - \setlength{\topsep}{0pt}
   - \setlength{\partopsep}{0pt}
   - \setlength{\itemsep}{0pt}
   - \setlength{\floatsep}{0pt}
   - \setlength{\intextsep}{2pt}
   - \setlength{\abovecaptionskip}{2pt}
   - \setlength{\belowcaptionskip}{0pt}
-->


<style type="text/css">
body,
code.bash{
  font-size: 8px;
}
pre {
  font-size: 8px
}
</style>

<!-- https://grants.nih.gov/grants/ElectronicReceipt/pdf_guidelines.htm -->


```{r setup, include=FALSE}
knitr::opts_chunk$set( cache=TRUE )
```

\pagenumbering{gobble}


<!--

Refer to:  https://faculty.med.virginia.edu/facultyaffairs/files/2015/05/Portfolio-checklist-for-depts-4-May-2016.pdf


Areas of Excellence:  Include supporting documentation as is appropriate for your track
and proposed rank. Omit sections that are not relevant.


6. Research Documentation
   a. Research statement: what you do, why you do it, where your work is going.
   b. Supporting documents may include: relevant sections of your CV, grant support,
      publications, review activities, presentations at meetings or other institutions, etc.

7. Reprints of 3 Publications.
   a. Many candidates elect to include a paragraph discussing why they picked these publications.

-->

<!--

Refer to slides 32-33 of https://faculty.med.virginia.edu/facultyaffairs/files/2015/05/Polishing-Portfolio-2015.pdf

Research Statement
• Be concise.
• General description so all members can understand what you do and why it is important.
• Refer to the important publications that illustrate the points (not all of them) in the statement.
• Emphasize progress since the last promotion action.
• Where is the work going and future plans

Research Activities
• Grant support (past, present and pending)
• Publications (with the annotations)
• Review activities – journals and study sections
• Presentations at meetings (international and national), and other institutions
• Posters vs. oral presentations (selected abstracts
• Indicate whether presentations were invited
• Workshops – show us you are the expert in the field

-->


\begin{center}
{\Large \bf Research Statement}  

{\em Nicholas J. Tustison}
\end{center}

As research support faculty in the Department of Radiology and Medical Imaging at
UVa, my primary research focus is the development of robust and accurate
software for large-scale processing of medical imaging data and corresponding analysis
strategies for these data.  To put it simply and generally, I am a data scientist
who operates at the nexus of "big data", statistical science (including machine
learning), and software development for gaining insight into human systems.  

## I.  Principal Developer and Contributor of The Insight Toolkit

Addressing the deficiency of image processing tools for analyzing the Visible
Human Project in 1999, the National Library of Medicine (NLM) of the National Institutes
of Health (NIH) funded the Insight Toolkit (ITK) initiative bringing together multiple
academic institutions and various industrial partners, such as GE Research.  This
collaborative effort resulted in the Insight Toolkit---a comprehensive, open-source suite of
implemented algorithms for medical image analysis.  Development and expansion continues
to the present and is heavily utilized by industry and academic groups worldwide and, due
to its generalizability, has been adopted by the French space agency (CNES) for the
processing of remote-sensing imagery.  

### A. Major developer of NIH-sponsored open-source software

I have provided several key developments to the Insight Toolkit.
These contributions are listed in the accompanying CV (Section IX, Subsection C)
_Open-Source Software Short Communications_.  Starting
with my first contribution in 2005 (_$N$-D $C^k$ B-Spline Scattered Data Approximation_),
I have continued to provide well-known, open-source algorithmic implementations to the Insight Toolkit
including my latest contribution made recently on August 27, 2016 (_Two Luis Miguel fans walk into a
bar in Nagoya ---> (yada, yada, yada) ---> an ITK-implementation of a popular
patch-based denoising filter_).  Other important contributions include
operations for image convolution (_Image Kernel Convolution_), faux colormapping
(_Meeting Andy Warhol Somewhere Over the Rainbow: RGB Colormapping and ITK_), and
fundamental measures for evaluating segmentation results (_Introducing Dice,
Jaccard, and Other Label Overlap Measures To ITK_).   These software classes have
been downloaded over 67,413 times (average number of downloads per publication = 2,931).  

### B. Inventor of the N4 method for MRI bias correction

Of all these contributions, perhaps my most significant is a method for removing
the low frequency inhomogeneity artifacts common to MR images as an important preprocessing step for
MR image analysis.  This algorithm is commonly referred to in the literature as
"N4" or "Nick's nonparametric nonuniform intensity normalization" which was
formally introduced in the following publication:

> Tustison NJ, Avants BB, Cook PA, Egan A, Zheng Y, Yushkevich PA, and Gee JC.  N4ITK: Improved N3 Bias Correction, _IEEE Trans Med Imaging_, 29(6):1310–1320, June 2010. Cited 367 times; IF = 3.390; Rank 5 out of 100 computer science, interdisciplinary applications, 12 out of 76 biomedical engineering, 18 out of 249 electrical & electronic engineering, 3 out of 24 imaging science & photographic technology, 21 out of 125 radiology, nuclear medicine & medical imaging.[^11]

[^11]: Included as a representative publication.  

It is a significant extension of the popular N3 algorithm[^1] (introduced in 1998
with currently ~3,000 citations).  Prior to the N4 formal publication, it was provided
as open-source software to the ITK community:

> Tustison NJ, Gee JC: N4ITK: Nick’s N3 ITK Implementation for MRI Bias Field Correction, _Insight Journal_, 2009, http://hdl.handle.net/10380/3053.

where it has been downloaded over 10,000 times.

[^1]:  Sled JG, Zijdenbos AP, and Evans AC.  A nonparametric method for automatic correction of intensity nonuniformity in MRI data.  _IEEE Trans Med Imaging_, 17(1):87-97, Feb 1998.

<!--
downloads <- c( 1696, 3191, 2885, 1694, 3711, 2007, 10546, 4892, 3029, 1627, 2133, 5031, 1888, 2586, 2246, 3181, 1833, 105, 2253, 1709, 2069, 3994, 3107 )

avg: 2931
sum: 67413
count: 23
-->

### C.  Co-investigator and principal developer of the ITKv4 image registration refactoring

Image registration (or the mapping of corresponding features between two images)
is a fundamental component in medical image processing and analysis.
In 2011 the NIH-NLM sponsored a large-scale funding effort to "modernize" the Insight
Toolkit.  One of the three major contracts was to provide modern image registration
techniques to the toolkit requiring a complete refactoring of the existing image registration
framework.  This contract was awarded to a joint team consisting of
myself and collaborators from the University of Pennsylvania (under the direction
 of Professor Jim Gee):  

> Sponsor:  	NIH-NLM  
> Title:    	_Fundamental Refactoring of Deformable Image Registration in ITK with Distributed Computing and GPU Acceleration_  
> Role:	    	Principle investigator of UVa subcontract  
> Period:    7/1/2011 – 6/30/2012  

This team provided several major image registration upgrades to the algorithmic
toolkit and I wrote a significant portion of the actual software code.  Not only
did we implement current image registration technologies for inclusion into the
toolkit but we also were responsible for new and innovative techniques:

>  Tustison NJ and Avants BB. Explicit B-spline regularization in diffeomorphic image registration. _Front Neuroinform_, 7:39, 2013.  Cited 21 times; IF = 3.261; Rank 8 out of 57 mathematical & computational biology, 105 out of 252 neurosciences.

>  Avants BB, Tustison NJ, Stauffer M, Song G, Wu B, and Gee JC. The Insight ToolKit Image Registration Framework. _Front Neuroinform_, 8:44, 2014.  Cited 29 times; IF = 3.261; Rank 8 out of 57 mathematical & computational biology, 105 out of 252 neurosciences.

### D.  Co-investigator and principal developer of _ITK-Lung:  A Software Framework for Lung Image Processing and Analysis_

Jim Gee and I recently submitted
an NIH R01 grant for the development of ITK-Lung, a set of open-source software
tools for CT, PET, MRI pulmonary image analysis based on the Insight ToolKit.
Specifically, we plan to provide core algorithms for specific pulmonary image
analysis tasks across multiple modalities, many of which I have implemented and
made available with
previous publications. These basic tasks include intra- and inter-modal pulmonary
image registration, template building for cross-sectional and longitudinal (i.e.,
respiratory cycle) analyses, functional and structural lung image segmentation,
perfusion analysis, and computation of quantitative image indices as potential
imaging biomarkers. These efforts would facilitate other NIH-sponsored projects
which interface specific pulmonary algorithms (e.g., CT nodule detection) with
clinical and research applications.  Over the course of this 5-year project, the
following UVa faculty will be engaged:

* Nicholas J. Tustison, DSc, Principal Investigator (50% / year)
* Kun Qing, PhD, Co-investigator (15% / year)
* Y. Michael Shim, MD, Co-investigator (2% / year)
* W. Gerald Teague, MD, Co-investigator (2% / year)

## II. Co-Founder and Developer of the Advanced Normalization Tools (ANTs)

In 2006 my longtime colleague, Dr. Brian Avants, and I co-founded the Advanced Normalization
Tools (ANTs). ANTs is popularly considered a state-of-the-art medical image registration and segmentation toolkit based on ITK.  It is used by multiple academic institutions, research facilities (e.g., the Allen
Brain Institute, the Montreal Neurological Institute, the Laboratory of Neuroimaging at the University
of Southern California), and industry leaders (e.g., IBM Watson, GE Research).  In addition to
providing well-performing basic processing components, we have also engineered advanced pipelines
for obtaining key biomarkers for specific applications.  The major publication
associated with this tool,

> Avants BB, Tustison NJ, Song G, Cook PA, Klein A, and Gee JC. A Reproducible Evaluation of ANTs Similarity Metric Performance in Brain Image Registration, NeuroImage, 54(3):2033–2044, February 2011. Cited 448 times; IF = 6.357; Rank 1 out of 14 neuroimaging, 24 out of 252 neurosciences, 3 out of 125 radiology, nuclear medicine & medical imaging.[^12]

is one of the most cited recent papers from the journal _NeuroImage_.

[^12]: Included as a representative publication.  


### A. The ANTs cortical thickness pipeline

Measuring the thickness of
the cortical gray matter of the brain from MRI has long been used for assessing various neuropathologies and
normal longitudinal changes in the brain.  Up until recently the only publicly available resource
for performing this type of measurement was a software program called "FreeSurfer" which is developed
and made available from Mass General Hospital of Harvard University.  Recently, however,
I (along with several colleagues) created an ANTs-based pipeline which outperformed
FreeSurfer on multiple, publicly available data sets.  This work is described in

>	Tustison NJ, Cook PA, Klein A, Song G, Das SR, Duda JT, Kandel BM, van Strien N, Stone JR, Gee JC, and Avants BB. Large-Scale Evaluation of ANTs and FreeSurfer Cortical Thickness Measurements. _NeuroImage_, 99:166-179, Oct 2014.  Cited 46 times; IF = 6.357; Rank 1 out of 14 neuroimaging, 24 out of 252 neurosciences, 3 out of 125 radiology, nuclear medicine & medical imaging.

and is currently being employed by multiple groups and several institutions.
All resulting quantities and corresponding scripts and analyses have been made publicly available
for external use.  In fact, these measurements were used recently for investigating other
hypotheses concerning the longitudinal development of the entorhinal cortex:

> Hasan KM, Mwangi B, Cao B, Keser Z, Tustison NJ, Kochunov P, Frye RE, Savatic M, and Soares J. Entorhinal cortex thickness across the human lifespan. J of Neuroimaging, 26(3) :278-82, May 2016.  Cited 0 times; IF = 1.734;  Rank 128 out of 192 clinical neurology, 12 out of 14 neuroimaging, and 65 out of 125 radiology, nuclear medicine & medical imaging.[^13]

[^13]: Included as a representative publication.  

### B. Participant in international medical image analysis competitions

Over the years our ANTs-based tools have won several international competitions for a wide variety of applications involving several key UVa collaborators:

* finished in the first rank in the Klein 2009 international brain mapping competition,[^2]

* finished first overall in the EMPIRE10 international lung mapping competition,[^3]

* was the standard registration tool for the MICCAI 2013 segmentation competitions,[^4]

* finished first in the BRATS 2013 challenge,[^5] and

* won the best paper award at the STACOM 2014 challenge.[^6]

[^2]:  Klein et al., Evaluation of 14 nonlinear deformation algorithms applied to human brain MRI registration. _NeuroImage_, 46(3):786-802, Jul 2009.

[^3]:  Murphy et al., Evaluation of registration methods on thoracic CT: the EMPIRE10 challenge. _IEEE Trans Med Imaging_, 30(11):1901-20, Nov 2011.

[^4]: http://www.miccai2013.org

[^5]: http://martinos.org/qtim/miccai2013/

[^6]: http://www.springer.com/us/book/9783319146775

We have provided these winning protocols to the public as open-source for continued
development.

### C. Educator via tutorials and other ANTs informational fora

I have given several workshops to disseminate a better hands-on knowledge of the various algorithms and pipelines of the ANTs and ITK toolkits.  These include the following:

* ANTs workshop, MD Anderson, Houston, TX, USA.  August 2016.

* ANTs Workshop for the Chronic Effects of Neurotrauma Consortium (CENC), Baylor College, Houston, TX, USA. October 2015.

* SimpleITK tutorial, MICCAI, Munich, Germany. October 2015.

* ANTs workshop, Laboratory of Neuroimaging, Marina Del Rey, USA.  July 2015.

* CREATE-MIA Summer Workshop, ANTs Workshop, Montreal, Canada.  May 2015.

* SPIE Medical Imaging Workshop, Open source tools for medical image analysis, San Diego, USA.  February 2012.

In addition to these workshops, I respond to several ANTs queries per week
originating from our Sourceforge or Github ANTs repositories.  These
inquiries range from instructions for specific programs to
providing analysis guidelines for large-scale studies.  

### D. Developer for the ANTsR project

ANTs (Advanced Normalization Tools) is designed to provide high performance image processing techniques for medical image analysis.  During the evolution of the toolkit, it became clear that robust statistical machinery was lacking for making inferences from data produced from ANTs processing and visualization.  As part of a collaborative effort, I am part of the ANTsR development team which provides an interface between ANTs and the R project for statistical computing and visualization thus providing a complete set of tools for multivariate image analysis. ANTsR intends to provide a modern framework for medical analytics, with a focus on imaging-assisted prediction and statistical power.  The ANTsR package is publicly available on the github project hosting service

##  III. Research Support

As research faculty, I have played a supportive role for the various faculty research efforts.  These include the following (with corresponding publications and other items of note):

### A. UVa collaborations

* As part of the Hyperpolarized Gas group at UVa, I support efforts for quantitative assessment of functional lung imaging using hyperpolarized gases.  Collaborators include Talissa Altes (now at University of Missouri, Columbia), John Mugler, Eduard de Lange, Kun Qing, Jaime Mata, Lucia Flors-Basco, W. Gerald Teague, and Mike Shim.
    * These collaborative efforts have resulted in several publications including the following:

    > Flors L, Mugler JP, De Lange EE, Miller GW, Mata JF, Tustison N, Ruset IC, Hersman WW, and Altes TA. Hyperpolarized Gas Magnetic Resonance Lung Imaging in Children and Young Adults, _J Thorac Imag_, 31(5):285-295, Sep 2016.  Cited 0 times; IF = 1.723; Rank 71 out of 124 radiology, nuclear medicine, and medical imaging.

    > Tustison NJ, Qing K, Wang C, Altes TA, and Mugler III JP. Atlas-based estimation of lung and lobar anatomy in proton MRI. _Magn Reson Med_, 76(1):315-20, Jul 2016.  Cited 1 times; IF = 3.571; Rank 20 out of 125 radiology, nuclear medicine & medical imaging

    > Altes TA, Mugler JP, III, Ruppert K, Tustison NJ, Gersbach J, Szentpetery S, Meyer CH, de Lange EE, and Teague WG. Clinical Correlates of Lung Ventilation in Asthmatic Children. _J Allergy Clin Immun_, 137(3) :789-796, Mar 2016.  Cited 2 times; IF = 11.476; Rank 1 out of 24 allergy, 6 out of 148 immunology.

    > Qing K, Altes TA, Tustison NJ, Feng X, Chen X, Mata JF, Miller GW, de Lange EE, Tobias WA, Cates GD, Jr., Brookeman JR, and Mugler JP, III. Rapid Acquisition of Helium-3 and Proton 3D Image Sets of the Human Lung in a Single Breath-hold using Compressed Sensing. _Magn Reson Med_, 74(4):1110-5, October 2015.  Cited 3 time; IF = 3.571; Rank 20 out of 125 radiology, nuclear medicine & medical imaging.

    > Teague WG, Tustison NJ, and Altes TA.  Ventilation Heterogeneity in Asthma. _J Asthma_, 51(7):677-84, Sept 2014.  Cited 7 times; IF = 1.854; Rank 18 out of 25 allergy, 39 out of 58 respiratory system.

    > Tustison NJ*, Avants BB, Altes TA, de Lange EE, Mugler III JP, and Gee JC. Ventilation-Based Segmentation of the Lungs Using Hyperpolarized 3He MRI, _J Magn Reson Imaging_, 34(4):831–841, October 2011. Cited 26 times; IF = 3.210; Rank 23 out of 125 radiology, nuclear medicine and medical imaging.

    > Tustison NJ, Altes TA, Song G, de Lange EE, Mugler III JP, and Gee JC. Feature Analysis of Hyperpolarized Helium-3 Pulmonary MRI: A Study of Asthmatics versus Non-Asthmatics, _Magn Reson Med_, 63(6):1448–1455, June 2010. Cited 31 times; IF = 3.571; Rank 20 out of 125 radiology, nuclear medicine & medical imaging.

    * Past funding sources:

    > Sponsor: NIH-NHLBI  
    > Title: Simultaneous Xe129 MRI of Regional Lung Ventilation and Gas Uptake in COPD  
    > Role:	Co-investigator  
    > Period: 	7/1/2011 – 5/31/2016  

    > Sponsor: NIH-NHLBI  
    > Title: Single-session bronchial thermoplasty for severe asthmatics guided by Hxe MRI
    > Role:		Principal investigator on UVa subcontract  
    > Period:     	9/1/2011 – 1/31/2015  

    > Sponsor: NIH-NHLBI  
    > Title:    		Regulatory Advancement of HXe as an MRI Contrast Agent  
    > Role:		Co-investigator  
    > Period:     	9/1/2011 – 1/31/2015  

    > Sponsor:  	Novartis Pharmaceuticals Corp.  
    > Title:    		Hyperpolarized noble-gas enhanced imaging of b2-agonist pharmacodynamics and pharmacokinetics in mild to moderate asthma  
    > Role:		Co-investigator  
    > Period:     	10/15/2010 – 5/31/2014  

    > Sponsor: 	Vertex Pharmaceuticals, Inc.  
    > Title:		A Phase II, Single-Blind, Placebo-Controlled Crossover Study to Evaluate the Effect of VX-770 on Hyperpolarized Helium-3 Magnetic Resonance Imaging in Subjects with Cystic Fibrosis, the G551D Mutation and FEV1 ≥40% Predicted  
    > Role:		Physicist  
    > Period:     	9/9/2010 – 9/8/2012  

    * In order to support ongoing software development efforts associated with these collaborations and other external collaborations at the University of Pennsylvania (cf Subsection D. External collaborations), my colleague Dr. James C. Gee and I recently (Oct. 2016) submitted an R01 grant titled  _ITK-Lung:  A Software Framework for Lung Image Processing and Analysis_ (cf Section I D).

    * Other current and pending grants:

    > Title: Hyperpolarized Xenon-129 MRI: a new multi-dimensional biomarker to determine pulmonary physiologic responses to COPD therapeutics  
    > Role:  		Co-investigator  
    > Period:  5 years  

    > Sponsor: NIH-NHLBI  
    > Title:  	Xe129 MRI of the lung:  A new technology to assess treatment for COPD  
    > Role:  		Co-investigator  
    > Period:  7/1/2016 – 6/30/2017  

* One of my principal collaborators is James Stone with whom I have been developing quantitative methods for traumatic brain injury although much of our work has been of much more general neuorimaging application.
    * These collaborative efforts have resulted in several publications including the following:

    >	Stone JR, Wilde EA, Taylor BA, Tate DF, Levin H, Bigler ED, Scheibel RS, Newsome MR, Mayer AR, Abildskov T, Black GM, Lennon MJ, York GE, Agarwal R, DeVillasante J, Ritter JL, Walker PB, Ahlers ST, and Tustison NJ. Supervised learning technique for the automated identification of white matter hyperintensities in traumatic brain injury, _Brain Inj_, In press.  Cited 0 times; IF = 1.822; Rank 187 out of 256 neurosciences and 17 out of 65 rehabilitation.

    > Wilde EA, Bigler ED, Huff TJ, Wang H, Black GM, Christensen Z, Goodrich-Hunsaker N, Petrie JA, Abildskov T, Taylor BA, Stone JR, Tustison NJ, Newsome MR, Levin HS, Chu ZD, York GE, and Tate DF. Quantitative Structural Neuroimaging of Mild Traumatic Brain Injury in the Chronic Effects of Neurotrauma Consortium (CENC): Comparison of Volumetric Data within and across Scanners, _Brain Inj_, In press.  Cited 0 times; IF = 1.822; Rank 187 out of 256 neurosciences and 17 out of 65 rehabilitation.

    > Tustison NJ, Cook PA, Klein A, Song G, Das SR, Duda JT, Kandel BM, van Strien N, Stone JR, Gee JC, and Avants BB. Large-Scale Evaluation of ANTs and FreeSurfer Cortical Thickness Measurements. _NeuroImage_, 99:166-179, Oct 2014.  Cited 46 times; IF = 6.357; Rank 1 out of 14 neuroimaging, 24 out of 252 neurosciences, 3 out of 125 radiology, nuclear medicine & medical imaging.

    > Tustison NJ, Avants BB, Cook PA, Kim J, Whyte J, Gee JC, and Stone JR. Logical Circularity in voxel-based analysis: normalization strategy may induce statistical bias. _Hum Brain Mapp_, 35:745-759, March 2014. Cited 21 times; IF = 5.969; Rank 2 out of 14 neuroimaging, 27 out of 252 neurosciences, 5 out of 125 radiology, nuclear medicine & medical imaging.

    * Past funding sources:

    > Sponsor:  	The Geneva Foundation  
    > Title:    		Brain Injury Biomarkers and Behavioral Characterization of mTBI in Soldiers Following Repeated, Low-Level Blast Exposure  
    > Role:		Co-investigator  
    > Period:     	1/1/2013 – 5/31/2015  

    > Sponsor:  	Naval Medical Research Center  
    > Title:    		Experienced Breacher Study  
    > Role:		Co-investigator – UVa subcontract  
    > Period:     	6/1/2012 – 5/30/2014  

    * Current and pending funding sources:

    > Sponsor:  	NASA/Medical University of South Carolina  
    > Title:    		Human Cerebral Vascular Autoregulation and Venous Outflow In Response to Microgravity-Induced Cephalad Fluid Redistribution  
    > Role:		Co-investigator  
    > Period:     	5/16/2013 – 5/15/2018  

    > Member Chronic Effects of Neurotrauma Consortium  
    > Funding period:  2/2016 - 8/2018  


* Other successful collaborations with UVa faculty include:

    * Automatic segmentation of brain tumor from multi-modal MRI with collaborators Max Wintermark (now at Stanford) and former radiology fellow Christopher Durst.  Our team won the international 2013 Multimodal Brain Tumor Segmentation Challenge (BRATS) which resulted in the following publications:

    >	Tustison NJ, Shrinhidi KL, Wintermark M, Durst CR, Kandel BM, Gee JC, Grossman MC, and Avants BB.  Optimal symmetric multimodal templates and concatenated random forests for supervised brain tumor segmentation (simplified) with ANTsR. Neuroinformatics, 13(2):209-225, April 2015.  Cited 17 times; IF =2.825; Rank 13 out of 102 computer science, interdisciplinary applications, 124 out of 252 neurosciences.

    > Menze BH, Jakab A, Bauer S, Kalpathy-Cramer J, Farahani K, Kirby J, Burren Y, Porz N, Slotboom J, Wiest R, Lanczi L, Gerstner E, Weber M-A, Arbel T, Avants BB, Ayache N, Buendia P, Collins DL, Cordier N, Corso JJ, Criminisi A, Das T, Delingete H, Demiralp C, Durst CR, Dojat M, Doyle S, Festa J, Forbes F, Geremia E, Glocker B, Golland P, Guo X, Hamamci A, Iftekharuddin KM, Jena R, John NM, Konukoglu E, Lashkari D, Mariz JA, Meier R, Pereira S, Precup D, Price SJ, Riklin-Raviv T, Reza SMS, Ryan M, Schwartz L, Shin H-C, Shotton J, Silva CA, Sousa N, Subbanna NK, Szekely G, Taylor TJ, Thomas OM, Tustison NJ, Unal G, Vasseur F, Wintermark M, Ye DH, Zhao L, Zhao B, Zikic D, Prastawa M, Reyes M, and Leemput KV. The Multimodal Brain Tumor Image Segmentation Benchmark (BRATS). IEEE Trans Med Imaging, 34(10):1993-2024, October 2015. Cited 131 times; IF = 3.390; Rank 5 out of 100 computer science, interdisciplinary applications, 12 out of 76 biomedical engineering, 18 out of 249 electrical & electronic engineering, 3 out of 24 imaging science & photographic technology, 21 out of 125 radiology, nuclear medicine & medical imaging.

    * ANTs image registration techniques are currently used as part of Mike Salerno's (Cardiac, Radiology & Medical Imaging, and Biomedical Engineering Departments) ongoing development of novel cardiac MRI acquisition techniques.  As part of this collaborative work, Mike and I won the best paper award at the Statistical Atlases and Computational Modelling of the Heart (STACOM) motion estimation challenge held in Boston, 2014 as part of the international Medical Image Computing and Computer-Assisted Intervention (MICCAI) conference.  

    * Recently, Tony Filiano and Jonathon Kipnis of the Neuroscience Department of UVa published a breakthrough paper in Nature concerning the relationship between immunity and social deficits.     I was instrumental in that publication in performing the resting state fMRI analysis using some of the software I developed within the ANTsR package:

    > Filiano AJ, Xu Y, Tustison NJ, Marsh RL, Baker W, Smirnov I, Overall CC, Gadani SP, Turner SD, Weng Z, Peerzade SN, Chen H, Lee KS, Scott MM, Beenhakker MP, Litvak V, and Kipnis J*. Unexpected role of interferon-γ in regulating neuronal connectivity and social behaviour, Nature, 535(7612):425-9, Jul 2016.  Cited 3 times; IF = 38.138; Rank 1 out of 63 multidisciplinary sciences.

    * Other current research collaborators include Spencer Payne and Larry Borish (Medicine), Carlos Leiva Salinas (Radiology and Medical Imaging), and Stuart Berr (Radiology & Medical Imaging and Biomedical Engineering).

###  B. External collaborations

* Jim Gee is an Associate Professor in the Department of Radiology at the University of
Pennsylvania  and the Director of the Penn Image Computing and Science Laboratory.  He was also my post-doc mentor from 2004 -- 2010.  We continue to work together on multiple projects including the ITK Lung grant previously described.  Short-term future plans include a planned ANTs software maintenance R01 grant to be submitted in the February 2017 cycle.  

* Mike Yassa is an Associate Professor in the Department of Neurobiology and Behavior and the Director of the Center for the Neurobiology of Learning & Member.  He runs the Yassa Translational Neurobiology Lab where I currently have a joint appointment with UC Irvine as a Visiting Assistant Researcher.  As a long-time user and promoter of the ANTs software, Mike and I have several shared projects related to Alzheimer's disease and other neurobiological research questions.  
